name: hello world!

on:
    push:
        branches:
            - master

jobs:
    hello_world_job:
        runs-on: ubuntu-latest
        steps:
            - name: say hello
              run: echo "hello world!"
            - name: get date
              run: date
            - name: get directory content
              run: ls -l